/* Since Then: a span of time squeezed into one day. Midnight is the start of the span and the next
 * midnight is now. Deep Time maps Earth's 4,540 million years; the historical lenses map 9700 BC,
 * 1 CE or 1001 CE to the present. All data is compiled in (deep_time_data.h, history_data.h: generated by
 * execution/ from data/). */
#include <pebble.h>
#include "deep_time_data.h"
#include "history_data.h"

#define DAY 86400
#define LAST_MINUTE (DAY - 60)
#define EARTH_YEARS 4540000000LL
#define UNIT_NAME 24
#define EVENT_LABEL 64
#define LENS_NAME 20
#define DEEP_UNIT_SIZE (4 + 4 + 1 + 1 + UNIT_NAME)
#define DEEP_EVENT_SIZE (4 + 1 + EVENT_LABEL)
#define HIST_LENS_SIZE (2 + LENS_NAME)
#define HIST_EVENT_SIZE (2 + 1 + 1 + EVENT_LABEL)
#define MAX_HIST 512
#define ROTATE_MS 333
#define STRIP_X 4
#define STRIP_W 192

enum { LENS_DEEP, LENS_HOLOCENE, LENS_CE, LENS_2M, LENS_COUNT };
enum { RANK_EON, RANK_ERA, RANK_PERIOD, RANK_EPOCH };
enum { PERSIST_LENS = 1, PERSIST_TIME_COLOR = 2 };

static const char *LENS_TITLES[LENS_COUNT] = {"DEEP TIME", "HOLOCENE", "COMMON ERA", "2ND MILLENNIUM"};

static Window *s_window;
static Layer *s_canvas;
static const uint8_t *s_deep, *s_hist;
static int s_deep_units, s_deep_events, s_hist_lenses, s_hist_events;
static int s_lens = LENS_DEEP;
static int s_time_hex = 0xFFFFFF; /* time digits, 0xRRGGBB from the settings colour picker */
static bool s_seconds;
static AppTimer *s_rotate_timer;
static int s_rot;

/* The current historical lens: indices of events in its span and their clock seconds. */
static int16_t s_span_idx[MAX_HIST];
static int32_t s_span_clock[MAX_HIST];
static int s_span_count;

/* ---------------- resource access ---------------- */

static uint32_t rd_u32(const uint8_t *p) { uint32_t v; memcpy(&v, p, 4); return v; }
static int16_t rd_i16(const uint8_t *p) { int16_t v; memcpy(&v, p, 2); return v; }

static const uint8_t *deep_unit(int i) { return s_deep + 8 + i * DEEP_UNIT_SIZE; }
static const uint8_t *deep_event(int i) { return s_deep + 8 + s_deep_units * DEEP_UNIT_SIZE + i * DEEP_EVENT_SIZE; }
static const uint8_t *hist_event(int i) { return s_hist + 8 + s_hist_lenses * HIST_LENS_SIZE + i * HIST_EVENT_SIZE; }

static int16_t hist_lens_start(int lens) { return rd_i16(s_hist + 8 + (lens - 1) * HIST_LENS_SIZE); }

static const uint8_t *table(const uint8_t *buf, size_t size, const char *magic, int *a, int *b) {
  if (size < 8 || memcmp(buf, magic, 4) != 0) return NULL;
  *a = buf[4] | (buf[5] << 8);
  *b = buf[6] | (buf[7] << 8);
  return buf;
}

/* ---------------- time ---------------- */

#ifdef ST_TEST_TOUR
/* Store screenshots: each wrist tap (pebble emu-tap) moves to the next pinned lens and time. */
static const struct { int lens; int seconds; } TOUR[] = {
  /* Second Millennium (1001 CE to now) across the day: the animated screenshot */
  {3, 3600}, {3, 10800}, {3, 18000}, {3, 25200}, {3, 32400}, {3, 39600}, {3, 46800},
  {3, 54000}, {3, 61200}, {3, 68400}, {3, 75600}, {3, 81000}, {3, 85500},
  /* Deep Time, Holocene and Common Era stills */
  {0, 40740}, {0, 85200}, {0, 86390},
  {1, 10800}, {1, 43200}, {1, 77400},
  {2, 21600}, {2, 43200}, {2, 79200},
};
#define TOUR_COUNT ((int)(sizeof(TOUR) / sizeof(TOUR[0])))
static int s_tour;
#endif

#ifdef ST_TEST_START_MINUTE
static int s_test_offset; /* whole minutes, so real minute ticks stay on the face's minute boundaries */
#endif

static int clock_seconds(struct tm *t) {
#ifdef ST_TEST_TOUR
  (void)t;
  return TOUR[s_tour].seconds;
#elif defined(ST_TEST_SECONDS)
  (void)t;
  return ST_TEST_SECONDS;
#else
  int tod = t->tm_hour * 3600 + t->tm_min * 60 + t->tm_sec;
#ifdef ST_TEST_START_MINUTE
  tod = (tod + s_test_offset + DAY) % DAY;
#endif
  return tod;
#endif
}

/* The present as thousandths of an astronomical year (2026.75 -> 2026750). */
static int64_t now_milli_year(struct tm *t, int tod) {
  int year = t->tm_year + 1900;
  bool leap = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
  int64_t day_secs = (int64_t)(leap ? 366 : 365) * DAY;
  int64_t into = (int64_t)t->tm_yday * DAY + tod;
  return (int64_t)year * 1000 + into * 1000 / day_secs;
}

static int64_t floor_div(int64_t a, int64_t b) { return a / b - ((a % b != 0) && ((a < 0) != (b < 0))); }

/* ---------------- lens state ---------------- */

static void build_span(struct tm *t, int tod) {
  s_span_count = 0;
  if (s_lens == LENS_DEEP || !s_hist) return;
  int64_t start = (int64_t)hist_lens_start(s_lens) * 1000;
  int64_t now = now_milli_year(t, tod);
  for (int i = 0; i < s_hist_events && s_span_count < MAX_HIST; i++) {
    int y = rd_i16(hist_event(i));
    int64_t a = (int64_t)(y > 0 ? y : y + 1) * 1000;
    if (a < start || a > now) continue;
    s_span_idx[s_span_count] = i;
    s_span_clock[s_span_count] = (int32_t)(DAY * (a - start) / (now - start));
    s_span_count++;
  }
}

/* Latest event at or before tod, as [first, last] of the group sharing its clock second. */
static bool latest_group(int tod, int *first, int *last) {
  int n = s_lens == LENS_DEEP ? s_deep_events : s_span_count;
  int found = -1;
  for (int i = 0; i < n; i++) {
    int32_t c = s_lens == LENS_DEEP ? (int32_t)rd_u32(deep_event(i)) : s_span_clock[i];
    if (c > tod) break;
    found = i;
  }
  if (found < 0) return false;
  int32_t c = s_lens == LENS_DEEP ? (int32_t)rd_u32(deep_event(found)) : s_span_clock[found];
  *last = found;
  *first = found;
  while (*first > 0) {
    int32_t p = s_lens == LENS_DEEP ? (int32_t)rd_u32(deep_event(*first - 1)) : s_span_clock[*first - 1];
    if (p != c) break;
    (*first)--;
  }
  return true;
}

/* ---------------- formatting ---------------- */

static void thousands(int64_t v, char *out, size_t size) {
  char digits[24];
  snprintf(digits, sizeof(digits), "%ld", (long)v);
  int len = strlen(digits), o = 0;
  for (int i = 0; i < len && o < (int)size - 1; i++) {
    out[o++] = digits[i];
    int left = len - i - 1;
    if (left > 0 && left % 3 == 0 && o < (int)size - 1) out[o++] = ',';
  }
  out[o] = '\0';
}

/* Deep Time age at tod: Ga at or above 1,000 Ma, Ma at or above 1 Ma, otherwise years. */
static void deep_age(int tod, char *num, size_t nsize, const char **unit) {
  int64_t years = EARTH_YEARS * (DAY - tod) / DAY;
  if (years >= 1000000000LL) {
    int64_t cga = years / 10000000LL; /* hundredths of a billion */
    snprintf(num, nsize, "%d.%02d", (int)(cga / 100), (int)(cga % 100));
    *unit = "billion years ago";
  } else if (years >= 1000000LL) {
    int64_t dma = years / 100000LL; /* tenths of a million */
    if (dma >= 100) snprintf(num, nsize, "%d", (int)(dma / 10));
    else snprintf(num, nsize, "%d.%d", (int)(dma / 10), (int)(dma % 10));
    *unit = "million years ago";
  } else {
    thousands(years, num, nsize);
    *unit = "years ago";
  }
}

static void format_year(int astro, bool approx, char *out, size_t size) {
  if (astro > 0) snprintf(out, size, "%s%d CE", approx ? "c. " : "", astro);
  else snprintf(out, size, "%s%d BCE", approx ? "c. " : "", 1 - astro);
}

static const char *ordinal(int n) {
  if (n % 100 >= 11 && n % 100 <= 13) return "th";
  switch (n % 10) { case 1: return "st"; case 2: return "nd"; case 3: return "rd"; default: return "th"; }
}

static void format_ago(int seconds, char *out, size_t size) {
  if (seconds < 60) snprintf(out, size, "%d s ago on this clock", seconds);
  else if (seconds < 3600) snprintf(out, size, "%d min ago on this clock", seconds / 60);
  else snprintf(out, size, "%dh %02dm ago on this clock", seconds / 3600, seconds / 60 % 60);
}

static GColor text_on(GColor bg) {
  int lum = 2 * bg.r + 5 * bg.g + bg.b; /* 2-bit channels, 0..24 */
  return lum >= 12 ? GColorBlack : GColorWhite;
}

/* ---------------- drawing ---------------- */

typedef struct { const char *name, *context; GColor color; } Band;

/* The band is the period, or the era or eon where no period is defined. Context below it: the epoch
 * (where one exists) and the era, or the eon under an era band. */
static Band deep_band(int tod, char *context, size_t size) {
  Band band = {"", "", GColorDarkGray};
  const uint8_t *at[RANK_EPOCH + 1] = {NULL};
  for (int i = 0; i < s_deep_units; i++) {
    const uint8_t *u = deep_unit(i);
    if (u[8] <= RANK_EPOCH && (int)rd_u32(u) <= tod && tod < (int)rd_u32(u + 4)) at[u[8]] = u;
  }
  int rank = at[RANK_PERIOD] ? RANK_PERIOD : at[RANK_ERA] ? RANK_ERA : RANK_EON;
  if (!at[rank]) return band;
  band.name = (const char *)(at[rank] + 10);
  band.color = (GColor){.argb = at[rank][9]};
  const char *above = rank == RANK_PERIOD && at[RANK_ERA] ? (const char *)(at[RANK_ERA] + 10)
                    : rank >= RANK_ERA && at[RANK_EON] ? (const char *)(at[RANK_EON] + 10) : "";
  if (rank == RANK_PERIOD && at[RANK_EPOCH]) snprintf(context, size, "%s, %s", (const char *)(at[RANK_EPOCH] + 10), above);
  else snprintf(context, size, "%s", above);
  band.context = context;
  return band;
}

static void draw_strip(GContext *ctx, int y, int tod, int64_t start_milli, int64_t now_milli) {
  GRect strip = GRect(STRIP_X, y, STRIP_W, 10);
  if (s_lens == LENS_DEEP) {
    for (int i = 0; i < s_deep_units; i++) {
      const uint8_t *u = deep_unit(i);
      if (u[8] != RANK_EON) continue;
      int x0 = STRIP_X + (int)((int64_t)rd_u32(u) * STRIP_W / DAY);
      int x1 = STRIP_X + (int)((int64_t)rd_u32(u + 4) * STRIP_W / DAY);
      graphics_context_set_fill_color(ctx, (GColor){.argb = u[9]});
      graphics_fill_rect(ctx, GRect(x0, y, x1 - x0, 10), 0, GCornerNone);
    }
  } else {
    graphics_context_set_fill_color(ctx, GColorDarkGray);
    graphics_fill_rect(ctx, strip, 0, GCornerNone);
    /* A tick at each century (CE lenses) or millennium (Holocene). */
    int step = s_lens == LENS_HOLOCENE ? 1000 : 100;
    graphics_context_set_stroke_color(ctx, GColorLightGray);
    /* yr counts calendar boundaries; BCE year N is astronomical 1 - N, so 9000 BCE sits at -8999. */
    int64_t first = floor_div(start_milli / 1000, step) * step + step;
    for (int64_t yr = first;; yr += step) {
      int64_t astro = yr <= 0 ? yr + 1 : yr;
      if (astro * 1000 >= now_milli) break;
      if (astro * 1000 <= start_milli) continue;
      int x = STRIP_X + (int)((astro * 1000 - start_milli) * STRIP_W / (now_milli - start_milli));
      graphics_draw_line(ctx, GPoint(x, y), GPoint(x, y + 9));
    }
  }
  int cx = STRIP_X + (int)((int64_t)tod * STRIP_W / DAY);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(cx - 1, y - 3, 3, 16), 0, GCornerNone);
}

static void canvas_update(Layer *layer, GContext *ctx) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  int tod = clock_seconds(t);
  GRect b = layer_get_bounds(layer);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, b, 0, GCornerNone);

  GFont small = fonts_get_system_font(FONT_KEY_GOTHIC_14);
  GFont body = fonts_get_system_font(FONT_KEY_GOTHIC_18);
  GFont bold = fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD);
  GFont big = fonts_get_system_font(FONT_KEY_GOTHIC_28_BOLD);

  /* Time bar: 24-hour on purpose; midnight to midnight is the span. */
  char time_text[16];
  if (s_seconds) snprintf(time_text, sizeof(time_text), "%02d:%02d:%02d", tod / 3600, tod / 60 % 60, tod % 60);
  else snprintf(time_text, sizeof(time_text), "%02d:%02d", tod / 3600, tod / 60 % 60);
  graphics_context_set_text_color(ctx, GColorFromHEX(s_time_hex));
  graphics_draw_text(ctx, time_text, fonts_get_system_font(FONT_KEY_LECO_26_BOLD_NUMBERS_AM_PM), GRect(6, 2, 130, 30), GTextOverflowModeFill, GTextAlignmentLeft, NULL);
  graphics_context_set_text_color(ctx, GColorLightGray);
  graphics_draw_text(ctx, LENS_TITLES[s_lens], small, GRect(100, 10, 96, 16), GTextOverflowModeTrailingEllipsis, GTextAlignmentRight, NULL);

  bool ready = s_lens == LENS_DEEP ? s_deep != NULL : s_hist != NULL;
  if (!ready) {
    graphics_draw_text(ctx, "data missing", body, GRect(6, 90, 188, 24), GTextOverflowModeFill, GTextAlignmentCenter, NULL);
    return;
  }

  /* Where on the span this moment falls. */
  char num[24];
  const char *unit = "";
  Band band = {"", "", GColorDarkGray};
  char band_text[32] = "", context_text[56] = "";
  int64_t start_milli = 0, now_milli = 0;
  if (s_lens == LENS_DEEP) {
    deep_age(tod, num, sizeof(num), &unit);
    band = deep_band(tod, context_text, sizeof(context_text));
  } else {
    start_milli = (int64_t)hist_lens_start(s_lens) * 1000;
    now_milli = now_milli_year(t, tod);
    int64_t at = start_milli + (now_milli - start_milli) * tod / DAY;
    int astro = (int)floor_div(at, 1000);
    format_year(astro, false, num, sizeof(num));
    char *space = strchr(num, ' ');
    if (space) { *space = '\0'; unit = astro > 0 ? "CE" : "BCE"; }
    if (s_lens == LENS_HOLOCENE) {
      /* ICS Holocene ages: Greenlandian to 6236 BC, Northgrippian to 2250 BC, then Meghalayan. */
      if (astro < -6235) { band.name = "Greenlandian"; band.color = GColorPastelYellow; }
      else if (astro < -2249) { band.name = "Northgrippian"; band.color = GColorIcterine; }
      else { band.name = "Meghalayan"; band.color = GColorRajah; }
      int millennium = astro > 0 ? (astro - 1) / 1000 + 1 : (-astro) / 1000 + 1;
      snprintf(context_text, sizeof(context_text), "%d%s millennium %s", millennium, ordinal(millennium), astro > 0 ? "CE" : "BCE");
      band.context = context_text;
    } else {
      int century = (astro - 1) / 100 + 1;
      snprintf(band_text, sizeof(band_text), "%d%s century", century, ordinal(century));
      band.name = band_text;
      band.color = century % 2 ? GColorCobaltBlue : GColorDukeBlue;
      int millennium = (astro - 1) / 1000 + 1;
      snprintf(context_text, sizeof(context_text), "%d%s millennium", millennium, ordinal(millennium));
      band.context = context_text;
    }
  }

  graphics_context_set_text_color(ctx, GColorWhite);
  GSize ns = graphics_text_layout_get_content_size(num, big, GRect(0, 0, 188, 34), GTextOverflowModeFill, GTextAlignmentLeft);
  graphics_draw_text(ctx, num, big, GRect(6, 30, ns.w + 2, 34), GTextOverflowModeFill, GTextAlignmentLeft, NULL);
  graphics_context_set_text_color(ctx, GColorLightGray);
  graphics_draw_text(ctx, unit, body, GRect(6 + ns.w + 6, 40, 188 - ns.w - 6, 22), GTextOverflowModeTrailingEllipsis, GTextAlignmentLeft, NULL);

  graphics_context_set_fill_color(ctx, band.color);
  graphics_fill_rect(ctx, GRect(0, 68, 200, 26), 0, GCornerNone);
  graphics_context_set_text_color(ctx, text_on(band.color));
  graphics_draw_text(ctx, band.name, bold, GRect(6, 69, 188, 22), GTextOverflowModeTrailingEllipsis, GTextAlignmentLeft, NULL);
  graphics_context_set_text_color(ctx, GColorLightGray);
  graphics_draw_text(ctx, band.context, small, GRect(6, 95, 188, 16), GTextOverflowModeTrailingEllipsis, GTextAlignmentLeft, NULL);

  /* The latest event; events sharing a clock second take turns. */
  int first, last;
  if (latest_group(tod, &first, &last)) {
    int i = first + s_rot % (last - first + 1);
    const char *label;
    char when[72], ago[48];
    int32_t clock;
    if (s_lens == LENS_DEEP) {
      const uint8_t *e = deep_event(i);
      clock = (int32_t)rd_u32(e);
      label = (const char *)(e + 5);
      format_ago(tod - clock, ago, sizeof(ago));
      snprintf(when, sizeof(when), "%s%s", (e[4] & 1) ? "~ " : "", ago);
    } else {
      const uint8_t *e = hist_event(s_span_idx[i]);
      clock = s_span_clock[i];
      label = (const char *)(e + 4);
      int y = rd_i16(e);
      char year[20];
      format_year(y > 0 ? y : y + 1, e[2] & 1, year, sizeof(year));
      format_ago(tod - clock, ago, sizeof(ago));
      snprintf(when, sizeof(when), "%s, %s", year, ago);
    }
    graphics_context_set_text_color(ctx, GColorWhite);
    graphics_draw_text(ctx, label, body, GRect(6, 114, 188, 46), GTextOverflowModeWordWrap, GTextAlignmentLeft, NULL);
    graphics_context_set_text_color(ctx, GColorChromeYellow);
    graphics_draw_text(ctx, when, small, GRect(6, 160, 188, 18), GTextOverflowModeTrailingEllipsis, GTextAlignmentLeft, NULL);
  }

  draw_strip(ctx, 194, tod, start_milli, now_milli);
  graphics_context_set_text_color(ctx, GColorLightGray);
  static const char *span_start[LENS_COUNT] = {"4.54 billion years ago", "9700 BCE", "1 CE", "1001 CE"};
  graphics_draw_text(ctx, span_start[s_lens], small, GRect(4, 208, 140, 16), GTextOverflowModeFill, GTextAlignmentLeft, NULL);
  graphics_draw_text(ctx, "now", small, GRect(150, 208, 46, 16), GTextOverflowModeFill, GTextAlignmentRight, NULL);
}

/* ---------------- ticking ---------------- */

static void ticked(struct tm *t, TimeUnits changed);

/* True while more than one event shares the latest clock second (only 23:59:59 in Deep Time). */
static bool shared_second(void) {
  time_t now = time(NULL);
  int first, last;
  return latest_group(clock_seconds(localtime(&now)), &first, &last) && last > first;
}

static void rotate(void *data) {
  s_rotate_timer = NULL;
  s_rot++;
  layer_mark_dirty(s_canvas);
  if (s_seconds && shared_second()) s_rotate_timer = app_timer_register(ROTATE_MS, rotate, NULL);
}

/* Minute ticks, except Deep Time's last minute, which ticks every second. */
static void choose_tick(int tod) {
  bool want = s_lens == LENS_DEEP && tod >= LAST_MINUTE;
  if (want == s_seconds) return;
  s_seconds = want;
  tick_timer_service_unsubscribe();
  tick_timer_service_subscribe(want ? SECOND_UNIT : MINUTE_UNIT, ticked);
  APP_LOG(APP_LOG_LEVEL_INFO, "tick: %s", want ? "seconds" : "minutes");
  if (!want && s_rotate_timer) { app_timer_cancel(s_rotate_timer); s_rotate_timer = NULL; }
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  int tod = clock_seconds(t);
  build_span(t, tod);
  choose_tick(tod);
  if (!s_seconds) s_rot++; /* minute ticks also take turns through a shared second */
  else if (!s_rotate_timer && shared_second()) {
    APP_LOG(APP_LOG_LEVEL_INFO, "rotate: on");
    s_rotate_timer = app_timer_register(ROTATE_MS, rotate, NULL);
  }
  layer_mark_dirty(s_canvas);
}

static void ticked(struct tm *t, TimeUnits changed) { refresh(); }

/* ---------------- settings ---------------- */

/* A settings value as an int: Clay sends selects as strings and colours as ints of any width. */
static bool tuple_int(Tuple *t, int *out) {
  if (!t) return false;
  if (t->type == TUPLE_CSTRING) *out = atoi(t->value->cstring);
  else if (t->length == 1) *out = t->type == TUPLE_INT ? t->value->int8 : t->value->uint8;
  else if (t->length == 2) *out = t->type == TUPLE_INT ? t->value->int16 : t->value->uint16;
  else if (t->length == 4) *out = t->type == TUPLE_INT ? (int)t->value->int32 : (int)t->value->uint32;
  else return false;
  return true;
}

static void inbox(DictionaryIterator *iter, void *context) {
  int v;
  if (tuple_int(dict_find(iter, MESSAGE_KEY_Setting_TimeColor), &v) && v >= 0 && v <= 0xFFFFFF) {
    s_time_hex = v;
    persist_write_int(PERSIST_TIME_COLOR, s_time_hex);
  }
  if (tuple_int(dict_find(iter, MESSAGE_KEY_Setting_Lens), &v) && v >= 0 && v < LENS_COUNT) {
    s_lens = v;
    persist_write_int(PERSIST_LENS, s_lens);
  }
  refresh();
}

/* ---------------- lifecycle ---------------- */

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  s_canvas = layer_create(layer_get_bounds(root));
  layer_set_update_proc(s_canvas, canvas_update);
  layer_add_child(root, s_canvas);
}

static void window_unload(Window *window) { layer_destroy(s_canvas); }

#ifdef ST_TEST_TOUR
static void tour_tap(AccelAxisType axis, int32_t direction) {
  s_tour = (s_tour + 1) % TOUR_COUNT;
  s_lens = TOUR[s_tour].lens;
  APP_LOG(APP_LOG_LEVEL_INFO, "tour %d", s_tour);
  refresh();
}
#endif

static void init(void) {
  if (persist_exists(PERSIST_LENS)) s_lens = persist_read_int(PERSIST_LENS);
  if (s_lens < 0 || s_lens >= LENS_COUNT) s_lens = LENS_DEEP;
  if (persist_exists(PERSIST_TIME_COLOR)) s_time_hex = persist_read_int(PERSIST_TIME_COLOR) & 0xFFFFFF;
#ifdef ST_TEST_LENS
  s_lens = ST_TEST_LENS;
#endif
#ifdef ST_TEST_START_MINUTE
  {
    time_t now = time(NULL);
    struct tm *t = localtime(&now);
    s_test_offset = ST_TEST_START_MINUTE * 60 - (t->tm_hour * 3600 + t->tm_min * 60);
  }
#endif
  s_deep = table(DEEP_TIME_DATA, sizeof(DEEP_TIME_DATA), "STN1", &s_deep_units, &s_deep_events);
  s_hist = table(HISTORY_DATA, sizeof(HISTORY_DATA), "HST1", &s_hist_lenses, &s_hist_events);
  s_window = window_create();
  window_set_background_color(s_window, GColorBlack);
  window_set_window_handlers(s_window, (WindowHandlers){.load = window_load, .unload = window_unload});
  window_stack_push(s_window, true);
  app_message_register_inbox_received(inbox);
  app_message_open(128, 32);
  tick_timer_service_subscribe(MINUTE_UNIT, ticked);
#ifdef ST_TEST_TOUR
  s_lens = TOUR[0].lens;
  s_time_hex = 0xFFFFFF; /* store shots use the default colour, whatever the emulator has saved */
  accel_tap_service_subscribe(tour_tap);
#endif
  refresh();
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  if (s_rotate_timer) app_timer_cancel(s_rotate_timer);
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
